"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { HUD } from "../../lib/hudTheme";

const TIERS=[{key:"review",label:"Top 100 Human Review",cap:100},{key:"candidates",label:"Top 500 Candidates",cap:500},{key:"contractor",label:"Top 20 Contractor Package",cap:20}];
const COUNTY_LABEL={hennepin:"Hennepin",ramsey:"Ramsey",dakota:"Dakota",scott:"Scott",carver:"Carver",anoka:"Anoka"};
const REVIEW_COLOR={pending:HUD.amber,approved:HUD.green,partial:HUD.cyan,rejected:HUD.red,needs_images:HUD.muted,contractor_sent:HUD.cyan};

export default function TwinCitiesPriorityPage(){
  const [tier,setTier]=useState("review"),[leads,setLeads]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(null),[meta,setMeta]=useState(null),[expanded,setExpanded]=useState(null),[imageLead,setImageLead]=useState(null),[crawling,setCrawling]=useState(false),[crawlStatus,setCrawlStatus]=useState(null),[query,setQuery]=useState(""),[confidenceFilter,setConfidenceFilter]=useState("all"),[autoRefresh,setAutoRefresh]=useState(true);
  const firstAutoSwarm=useRef(false);

  const load=useCallback(async(t)=>{setLoading(true);setError(null);try{const res=await fetch(`/api/top-leads?tier=${t}&_=${Date.now()}`,{cache:"no-store"});const data=await res.json();if(!data.ok)throw new Error(data.error||"Unable to load leads");setLeads(data.leads||[]);setMeta({scanned:data.scanned,entered:data.entered,cap:data.cap,top100Count:data.top100Count,top500Count:data.top500Count});}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
  useEffect(()=>{load(tier)},[tier,load]);
  useEffect(()=>{if(!autoRefresh)return;const id=setInterval(()=>load(tier),60000);return()=>clearInterval(id)},[autoRefresh,tier,load]);

  async function runEvidenceCycle(auto=false){if(crawling)return;setCrawling(true);setCrawlStatus({ok:true,message:auto?"Auto-swarm is strengthening the weakest top-ranked properties…":"Searching permits, storm/weather, assessor data and imagery for unresolved properties…"});try{const res=await fetch("/api/twincities/evidence-cycle",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({limit:auto?6:12})});const data=await res.json();setCrawlStatus({ok:!!data.ok,message:data.ok?`Evidence swarm processed ${data.processed}; ${data.persisted??data.processed} persisted. Confidence refreshed.`:(data.error||"Evidence cycle failed")});if(data.ok)await load(tier)}catch(e){setCrawlStatus({ok:false,message:e.message})}finally{setCrawling(false)}}
  useEffect(()=>{if(firstAutoSwarm.current||loading||!leads.length)return;const weak=leads.filter(l=>Number(l.confidenceScore||0)<50).length;if(tier==="review"&&weak>=Math.min(10,Math.ceil(leads.length*.35))){firstAutoSwarm.current=true;runEvidenceCycle(true)}},[loading,leads,tier]);

  function chooseTier(next){if(next===tier)load(next);else setTier(next);setExpanded(null)}
  async function setReviewStatus(id,status){setLeads(cur=>cur.map(l=>l.id===id?{...l,reviewStatus:status}:l));try{const r=await fetch("/api/lead-review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok)throw new Error("Review update failed") }catch(e){setCrawlStatus({ok:false,message:e.message})}}

  const metrics=useMemo(()=>{const total=leads.length||1;const avg=Math.round(leads.reduce((s,l)=>s+Number(l.confidenceScore||0),0)/total);return{avg,ready:leads.filter(l=>Number(l.confidenceScore||0)>=70).length,needs:leads.filter(l=>Number(l.confidenceScore||0)<50).length,images:leads.filter(l=>l.sourceStatus?.imagery||l.imageUrl).length}},[leads]);
  const filtered=useMemo(()=>leads.filter(l=>{const text=`${l.address||""} ${l.city||""} ${l.county||""}`.toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;const c=Number(l.confidenceScore||0);if(confidenceFilter==="ready"&&c<70)return false;if(confidenceFilter==="building"&&(c<35||c>=70))return false;if(confidenceFilter==="weak"&&c>=35)return false;return true}),[leads,query,confidenceFilter]);

  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 82% 0,rgba(0,240,255,.10),transparent 32%),linear-gradient(180deg,#03080d 0%,#061019 45%,#020609 100%)",color:HUD.ice,fontFamily:HUD.fontMono,padding:"clamp(12px,2vw,24px)"}}>
    <div style={{maxWidth:1600,margin:"0 auto"}}>
      <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"end",flexWrap:"wrap",marginBottom:18}}><div><div style={{fontSize:10,letterSpacing:".20em",color:HUD.cyan}}>AEROLEADAI / LIVE PROPERTY INTELLIGENCE</div><h1 style={{fontFamily:HUD.fontDisplay,fontSize:"clamp(28px,4vw,54px)",lineHeight:.95,margin:"7px 0",color:HUD.ice}}>Twin Cities Priority Engine</h1><div style={{fontSize:11,color:HUD.muted,maxWidth:850}}>Top 100 is the human-review front line. Top 500 is the ranked machine pool. Evidence, imagery, scorecards and contractor-ready properties stay visible in one command center.</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>setAutoRefresh(v=>!v)} style={button(autoRefresh?HUD.green:HUD.lineDim,autoRefresh?HUD.green:HUD.muted)}>{autoRefresh?"● LIVE 60s":"○ LIVE OFF"}</button><button onClick={()=>load(tier)} style={button(HUD.green,HUD.green)}>↻ REFRESH</button></div></header>

      <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginBottom:14}}><Metric label="VISIBLE" value={leads.length}/><Metric label="AVG CONFIDENCE" value={`${metrics.avg}%`} tone={metrics.avg>=70?HUD.green:HUD.amber}/><Metric label="70%+ READY" value={metrics.ready} tone={HUD.green}/><Metric label="UNDER 50%" value={metrics.needs} tone={metrics.needs?HUD.amber:HUD.green}/><Metric label="IMAGERY" value={metrics.images} tone={HUD.cyan}/></section>

      <div style={{display:"flex",gap:9,flexWrap:"wrap",marginBottom:12}}>{TIERS.map(t=><button key={t.key} onClick={()=>chooseTier(t.key)} style={button(tier===t.key?HUD.cyan:HUD.lineDim,tier===t.key?HUD.cyan:HUD.muted)}>{t.label}</button>)}<button onClick={()=>window.location.href="/twincities/contractor-prospects"} style={button(HUD.green,HUD.green)}>🏠 CONTRACTOR COMMAND</button><button onClick={()=>window.location.href="/twincities/apex10"} style={button(HUD.amber,HUD.amber)}>🎯 APEX REPORT</button><button disabled={crawling} onClick={()=>runEvidenceCycle(false)} style={{...button(HUD.cyan,HUD.cyan),opacity:crawling?.55:1}}>{crawling?"🧠 SEARCHING…":"🧠 RUN EVIDENCE SWARM"}</button></div>

      <div style={{display:"grid",gridTemplateColumns:"minmax(220px,1fr) 180px",gap:8,marginBottom:12}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search address, city or county…" style={{background:"rgba(2,8,12,.8)",border:`1px solid ${HUD.lineDim}`,color:HUD.ice,borderRadius:7,padding:"10px 12px",fontFamily:HUD.fontMono,outline:"none"}}/><select value={confidenceFilter} onChange={e=>setConfidenceFilter(e.target.value)} style={{background:"#051017",border:`1px solid ${HUD.lineDim}`,color:HUD.ice,borderRadius:7,padding:"10px 12px",fontFamily:HUD.fontMono}}><option value="all">All confidence</option><option value="ready">70%+ ready</option><option value="building">35–69% building</option><option value="weak">Under 35%</option></select></div>

      {meta&&<div style={{fontSize:10,color:HUD.muted,marginBottom:10}}>Scanned {meta.scanned??0} · Ranked {meta.entered??0} · Top 100 {meta.top100Count??0}/100 · Top 500 {meta.top500Count??0}/500 · Showing {filtered.length}/{leads.length}</div>}
      {crawlStatus&&<div style={{fontSize:10,color:crawlStatus.ok?HUD.green:HUD.red,marginBottom:12,padding:"9px 11px",border:`1px solid ${crawlStatus.ok?HUD.green:HUD.red}`,borderRadius:7,background:"rgba(0,0,0,.18)"}}>{crawlStatus.message}</div>}
      {loading&&<div style={{color:HUD.cyan,fontSize:11,marginBottom:10}}>RANKING + RENDERING PROPERTIES…</div>}
      {error&&<div style={{color:HUD.red,fontSize:11,marginBottom:10}}>Error: {error}</div>}

      <div style={{display:"flex",flexDirection:"column",gap:10}}>{filtered.map((lead,idx)=><LeadRow key={lead.id||`${lead.address}-${idx}`} lead={lead} idx={idx} tier={tier} expanded={expanded===lead.id} toggle={()=>setExpanded(expanded===lead.id?null:lead.id)} openImage={()=>setImageLead(lead)} review={setReviewStatus}/>)}</div>
      {!loading&&!filtered.length&&<div style={{padding:30,textAlign:"center",border:`1px dashed ${HUD.lineDim}`,borderRadius:9,color:HUD.muted}}>No properties match this view.</div>}
    </div>{imageLead&&<ImageViewer lead={imageLead} close={()=>setImageLead(null)}/>} 
  </main>
}

function Metric({label,value,tone=HUD.cyan}){return <div style={{border:`1px solid ${HUD.lineDim}`,borderRadius:8,padding:"11px 12px",background:"rgba(4,15,22,.72)",boxShadow:"0 14px 42px rgba(0,0,0,.18)"}}><div style={{fontSize:9,color:HUD.muted,letterSpacing:".10em"}}>{label}</div><div style={{fontSize:24,fontWeight:900,color:tone,marginTop:4}}>{value}</div></div>}
function LeadRow({lead,idx,tier,expanded,toggle,openImage,review}){const status=lead.sourceStatus||{};const sourceCount=[status.permit,status.storm,status.assessor,status.imagery].filter(Boolean).length;return <article style={{border:`1px solid ${expanded?HUD.cyan:HUD.lineDim}`,borderRadius:9,background:"rgba(5,14,20,.82)",overflow:"hidden",boxShadow:expanded?"0 18px 60px rgba(0,238,238,.06)":"0 10px 35px rgba(0,0,0,.18)"}}><div style={{display:"grid",gridTemplateColumns:"44px 84px minmax(220px,1.2fr) minmax(210px,.8fr) 90px 118px",gap:12,alignItems:"center",padding:"12px 13px",overflowX:"auto"}}><div style={{color:HUD.cyan,fontSize:13,fontWeight:900}}>#{lead.rank||idx+1}</div><button onClick={openImage} title="Open property imagery" style={{padding:0,border:`1px solid ${HUD.lineDim}`,borderRadius:6,overflow:"hidden",height:72,width:72,background:"#020608",cursor:"zoom-in"}}>{lead.imageUrl?<img src={lead.imageUrl} alt={lead.address} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/>:<span style={{fontSize:9,color:HUD.muted}}>NO IMAGE</span>}</button><div><div style={{fontSize:13,fontWeight:800,lineHeight:1.25,minWidth:230}}>{lead.address}</div><div style={{fontSize:10,color:HUD.muted,marginTop:3}}>{lead.city} · {COUNTY_LABEL[lead.county]||lead.county} County</div><div style={{fontSize:9,color:lead.imageIsFallback?HUD.amber:HUD.green,marginTop:4}}>{lead.imageIsFallback?"ESRI FALLBACK — CLICK TO INSPECT":"PROVIDER/CACHED IMAGE — CLICK TO INSPECT"}</div></div><div><div style={{fontSize:10,color:HUD.muted}}>Evidence <b style={{color:HUD.ice}}>{lead.evidenceScore}</b> · Confidence <b style={{color:lead.confidenceScore>=70?HUD.green:lead.confidenceScore>=35?HUD.amber:HUD.red}}>{lead.confidenceScore}%</b></div><div style={{display:"flex",gap:4,flexWrap:"wrap",marginTop:7}}><SourcePill label="PERMIT" ok={status.permit}/><SourcePill label="STORM" ok={status.storm}/><SourcePill label="VALUE" ok={status.assessor}/><SourcePill label="IMAGE" ok={status.imagery}/></div><div style={{fontSize:9,color:HUD.muted,marginTop:5}}>{sourceCount}/4 machine evidence lanes complete</div></div><div style={{fontSize:20,fontWeight:900,color:HUD.cyan,textAlign:"right"}}>{lead.priorityScore}</div><div style={{display:"flex",flexDirection:"column",gap:6,alignItems:"stretch"}}><span style={{fontSize:9,fontWeight:800,padding:"5px 7px",borderRadius:12,textAlign:"center",color:REVIEW_COLOR[lead.reviewStatus]||HUD.muted,border:`1px solid ${REVIEW_COLOR[lead.reviewStatus]||HUD.muted}`}}>{String(lead.reviewStatus||"pending").toUpperCase()}</span><button onClick={toggle} style={button(HUD.cyan,HUD.cyan)}>{expanded?"HIDE":"SCORECARD"}</button></div></div>{expanded&&<Scorecard lead={lead} tier={tier} review={review} openImage={openImage}/>}</article>}
function Scorecard({lead,tier,review,openImage}){const status=lead.sourceStatus||{};return <div style={{borderTop:`1px solid ${HUD.lineDim}`,padding:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,background:"rgba(0,0,0,.22)"}}><Panel title="WHY THIS RANK"><div style={{fontSize:12}}>Priority score <b style={{color:HUD.cyan}}>{lead.priorityScore}</b></div><div style={{fontSize:10,color:HUD.muted,marginTop:6}}>Evidence {lead.evidenceScore} · Confidence {lead.confidenceScore}% · Tier {lead.tier||"—"}</div><div style={{marginTop:8}}>{Object.entries(lead.breakdown||{}).map(([k,v])=><div key={k} style={{fontSize:10,color:HUD.muted,margin:"3px 0"}}>{k.replace(/_/g," ")}: <b style={{color:HUD.ice}}>{String(v)}</b></div>)}</div></Panel><Panel title="CONFIDENCE SOURCES"><SourceLine label="Permit search" ok={status.permit}/><SourceLine label="Storm/weather search" ok={status.storm}/><SourceLine label="Assessor/value" ok={status.assessor}/><SourceLine label="Imagery evidence" ok={status.imagery}/><div style={{fontSize:9,color:HUD.muted,marginTop:7}}>Confidence only rises when an evidence lane is actually completed.</div></Panel><Panel title="PROPERTY"><div style={{fontSize:10,color:HUD.muted}}>Assessed value</div><div style={{fontSize:17,fontWeight:800,marginTop:3}}>{lead.assessedValue?`$${Number(lead.assessedValue).toLocaleString()}`:"Not enriched"}</div><button onClick={openImage} style={{...button(HUD.cyan,HUD.cyan),marginTop:10}}>OPEN IMAGE</button><a href={lead.googleMapsUrl} target="_blank" rel="noreferrer" style={{...button(HUD.green,HUD.green),display:"block",textAlign:"center",textDecoration:"none",marginTop:7}}>OPEN GOOGLE MAPS ↗</a></Panel><Panel title="HUMAN REVIEW"><div style={{fontSize:10,color:HUD.muted,marginBottom:8}}>Review the evidence, then mark the property without leaving the scorecard.</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button onClick={()=>review(lead.id,"approved")} style={button(HUD.green,HUD.green)}>APPROVE</button><button onClick={()=>review(lead.id,"partial")} style={button(HUD.cyan,HUD.cyan)}>PARTIAL</button><button onClick={()=>review(lead.id,"needs_images")} style={button(HUD.amber,HUD.amber)}>NEEDS IMAGE</button><button onClick={()=>review(lead.id,"rejected")} style={button(HUD.red,HUD.red)}>REJECT</button></div>{tier==="review"&&<div style={{fontSize:9,color:HUD.amber,marginTop:8}}>Human review complements machine evidence; it does not replace missing evidence.</div>}</Panel></div>}
function ImageViewer({lead,close}){return <div onClick={close} style={{position:"fixed",inset:0,zIndex:9999,background:"rgba(0,0,0,.90)",display:"grid",placeItems:"center",padding:14}}><div onClick={e=>e.stopPropagation()} style={{width:"min(1160px,97vw)",maxHeight:"94vh",overflow:"auto",background:"#041016",border:`1px solid ${HUD.cyan}`,borderRadius:10,padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",marginBottom:10}}><div><b>{lead.address}</b><div style={{fontSize:9,color:HUD.muted}}>Full property view · Confidence {lead.confidenceScore}% · Score {lead.priorityScore}</div></div><button onClick={close} style={button(HUD.red,HUD.red)}>CLOSE ✕</button></div>{lead.imageUrl?<img src={lead.imageUrl} alt={lead.address} style={{width:"100%",maxHeight:"70vh",objectFit:"contain",background:"#000",display:"block"}}/>:<div style={{height:400,display:"grid",placeItems:"center",color:HUD.muted}}>No image available yet.</div>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{lead.imageUrl&&<a href={lead.imageUrl} target="_blank" rel="noreferrer" style={{...button(HUD.cyan,HUD.cyan),textDecoration:"none"}}>OPEN IMAGE SOURCE ↗</a>}<a href={lead.googleMapsUrl} target="_blank" rel="noreferrer" style={{...button(HUD.green,HUD.green),textDecoration:"none"}}>OPEN ADDRESS IN GOOGLE MAPS ↗</a></div></div></div>}
function Panel({title,children}){return <div style={{border:`1px solid ${HUD.lineDim}`,borderRadius:7,padding:11,background:"rgba(4,15,22,.45)"}}><div style={{fontSize:10,color:HUD.cyan,fontWeight:900,letterSpacing:".08em",marginBottom:8}}>{title}</div>{children}</div>}
function SourcePill({label,ok}){return <span style={{fontSize:8,padding:"3px 5px",borderRadius:8,border:`1px solid ${ok?HUD.green:HUD.lineDim}`,color:ok?HUD.green:HUD.muted}}>{ok?"✓":"○"} {label}</span>}
function SourceLine({label,ok}){return <div style={{display:"flex",justifyContent:"space-between",gap:8,fontSize:10,padding:"4px 0",color:HUD.muted}}><span>{label}</span><b style={{color:ok?HUD.green:HUD.amber}}>{ok?"COMPLETE":"SEARCH NEEDED"}</b></div>}
function button(border,color){return {padding:"8px 11px",borderRadius:6,cursor:"pointer",fontSize:10,fontWeight:800,border:`1px solid ${border}`,background:"rgba(0,0,0,.16)",color}}
