import { supabaseServer } from "../../../lib/supabaseServer";
import { calculatePriority } from "../../../lib/twincities/priorityEngine";
import { requestPropertyData,findRequestId,getPropertyResult,extractPropertyImages } from "../../../lib/eagleview";
export const dynamic="force-dynamic";export const maxDuration=60;
const FALLBACK_PROSPECTS=[{business_name:"APEX Exteriors LLC",prospect_score:96,service_area_cities:["Apple Valley","Eagan","Burnsville","Lakeville","Rosemount"]},{business_name:"Incline Exteriors",prospect_score:92,service_area_cities:["Excelsior","Deephaven","Minnetonka","Chanhassen","Chaska","Edina","Eden Prairie","Wayzata"]},{business_name:"Grussing Roofing & Exteriors",prospect_score:91,service_area_cities:["Eden Prairie","Edina","Saint Louis Park","Chaska","Chanhassen","Maple Grove","Bloomington"]},{business_name:"Storm ReNu",prospect_score:90,service_area_cities:["Bloomington","Richfield","Edina","Eagan","Burnsville"]},{business_name:"Keyprime Roofing and Remodeling",prospect_score:89,service_area_cities:["Golden Valley","Robbinsdale","Saint Louis Park","Plymouth","Maple Grove","Minneapolis"]}];
const EV=["property_data_id_003","property_data_id_004","property_data_id_008","property_data_id_009"],sleep=ms=>new Promise(r=>setTimeout(r,ms));
function score(row){const x=calculatePriority({county:row.county,yearBuilt:row.year_built,permit_within_10y:row.permit_within_10y,permitChecked:["verified","none_found"].includes(row.permit_evidence_status)||!!row.permit_checked_at||!!row.permit_notes,stormChecked:row.weather_evidence_status==="verified"||row.storm_evidence_status==="verified"||!!row.weather_checked_at||!!row.storm_checked_at||!!row.storm_date,assessorChecked:Number(row.assessed_value||0)>0,imageryChecked:["verified","fetched","ready","reviewed"].includes(String(row.image_evidence_status||"").toLowerCase())||!!row.image_fetched_at,hailInches:row.hail_inches,windMph:row.wind_mph,assessedValue:row.assessed_value,reviewStatus:row.review_status,roofEstimateUsd:row.replacement_cost??null,treeOverhang:(row.tree_score??0)>=50,largeOverhang:(row.tree_score??0)>=80,drivewayCrackRisk:(row.driveway_score??0)>=50});const stored=Math.max(Number(row.priority_score||0),Number(row.evidence_fusion_score||0),Number(row.opportunity_score||0),Number(row.necessity_score||0));return{...row,_score:Math.max(x.priorityScore||0,stored),evidenceScore:x.evidenceScore||Number(row.evidence_score||0),confidenceScore:Math.max(x.confidenceScore||0,Number(row.evidence_confidence||0),Number(row.confidence_score||0)),entered:x.entered||stored>0}}
function key(r){return String(r.parcel_id||r.property_id||r.apn||r.address_normalized||r.address||`${r.lat},${r.lon}`).toLowerCase().replace(/[^a-z0-9]/g,"")}
function residential(r){const t=String(r.property_type||r.property_class||r.property_use_type||"").toLowerCase(),a=String(r.address||"").toLowerCase();return !/(apartment|multi[- ]?family|multifamily|condo|townhome|townhouse|commercial|retail|office|industrial|hotel)/.test(t)&&!/\b(apt|unit|suite|ste)\b/.test(a)}
function clean(rows){const s=new Set();return rows.filter(residential).filter(r=>{const k=key(r);if(!k||s.has(k))return false;s.add(k);return true})}
async function imagery(l){try{const address=[l.address,l.city,l.state||"MN",l.zip].filter(Boolean).join(", ");const sub=await requestPropertyData({address,lat:l.lat,lon:l.lon,productIds:EV}),id=findRequestId(sub);if(!id)return{...l,images:[],image_status:"QUEUED"};const start=Date.now();let data=null;while(Date.now()-start<7000){const r=await getPropertyResult(id),st=String(r?.data?.request?.status||r?.data?.status||"").toLowerCase();if(r?.status===200&&st!=="in progress"&&st!=="processing"){data=r.data;break}await sleep(700)}const images=extractPropertyImages(data).map(x=>({...x,proxyUrl:`/api/eagleview?imageToken=${encodeURIComponent(x.token)}`}));return{...l,images,image_status:images.length?"READY":"QUEUED"}}catch{return{...l,images:[],image_status:"QUEUED"}}}
async function enrich(rows){return Promise.all(rows.map(imagery))}
export async function GET(req){const {searchParams}=new URL(req.url),name=searchParams.get("name"),db=supabaseServer();if(!db)return Response.json({ok:true,prospects:FALLBACK_PROSPECTS,contractor:null,leads:[]});try{let cq=db.from("contractor_candidates").select("*").eq("prospect",true).order("prospect_score",{ascending:false});if(name)cq=cq.eq("business_name",name);const {data,error}=await cq;if(error)throw error;const list=data||[],selected=name?list[0]:null;if(name&&!selected)return Response.json({ok:false,error:"Contractor not found"},{status:404});let leads=[],territoryFallback=false;if(selected){const cities=(selected.service_area_cities||[]).filter(Boolean);let q=db.from("batch_leads").select("*").eq("sales_status","new").neq("review_status","rejected").limit(2500);if(cities.length)q=q.in("city",cities);let r=await q;if(r.error)throw r.error;let ranked=clean((r.data||[]).map(score).filter(x=>x._score>0).sort((a,b)=>b._score-a._score));if(ranked.length<100){territoryFallback=true;const fb=await db.from("batch_leads").select("*").eq("sales_status","new").neq("review_status","rejected").order("priority_score",{ascending:false}).limit(1500);if(!fb.error){const used=new Set(ranked.map(key));for(const x of clean((fb.data||[]).map(score).filter(x=>x._score>0).sort((a,b)=>b._score-a._score))){if(ranked.length>=100)break;if(!used.has(key(x))){used.add(key(x));ranked.push({...x,territory_fallback:true})}}}}const visible=ranked.slice(0,100),eager=await enrich(visible.slice(0,6));leads=[...eager,...visible.slice(6).map(x=>({...x,images:[],image_status:"QUEUED"}))];}return Response.json({ok:true,prospects:list.length?list:FALLBACK_PROSPECTS,contractor:selected,leads,territoryFallback,network:"TWIN_CITIES",capacity:100})}catch(e){return Response.json({ok:true,prospects:FALLBACK_PROSPECTS,contractor:null,leads:[],note:e.message})}}
