"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

const C={bg:"#03080d",panel:"#071119",panel2:"#0a1720",line:"#153843",cyan:"#2ef0ea",green:"#4dffaf",amber:"#ffd166",red:"#ff6f84",text:"#edfaff",muted:"#78949d"};
const WINDOW_COLOR={NOW:C.red,"0-3 MONTHS":C.amber,"3-6 MONTHS":C.cyan,"6-12 MONTHS":"#6b98ff",WATCH:"#60717a"};
const imageCache=new Map();

async function acquireImagery(lead){
  if(imageCache.has(lead.id))return imageCache.get(lead.id);
  const address=[lead.address,lead.city,lead.state,lead.zip].filter(Boolean).join(", ");
  const promise=fetch("/api/eagleview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address,lat:lead.lat,lon:lead.lon,wait:true,maxWaitMs:18000})})
    .then(r=>r.json()).then(j=>({ok:!!j.ok,images:j.images||[],error:j.ok?null:(j.error||"Imagery unavailable")}))
    .catch(e=>({ok:false,images:[],error:e.message||"Imagery request failed"}));
  imageCache.set(lead.id,promise);return promise;
}
function useImageQueue(leads,concurrency=4){
  const[states,setStates]=useState({});const sig=leads.map(x=>x.id).join("|");
  useEffect(()=>{let cancelled=false,index=0;async function worker(){while(!cancelled&&index<leads.length){const lead=leads[index++];setStates(s=>({...s,[lead.id]:s[lead.id]||{status:"acquiring",images:[]}}));const result=await acquireImagery(lead);if(!cancelled)setStates(s=>({...s,[lead.id]:{status:result.images.length?"ready":"unavailable",...result}}));}}Array.from({length:Math.min(concurrency,leads.length)},worker);return()=>{cancelled=true};},[sig,concurrency]);return states;
}
function Gauge({label,value,suffix=""}){return <div style={{border:`1px solid ${C.line}`,padding:10,borderRadius:8,background:C.panel2}}><small style={{color:C.muted,fontSize:9,letterSpacing:1.2}}>{label}</small><b style={{display:"block",fontSize:20,color:C.text,marginTop:2}}>{value??"—"}{suffix}</b></div>}
function Tag({children,hot}){return <span style={{background:"#001015e8",border:`1px solid ${hot?C.red:C.line}`,color:hot?C.red:C.text,padding:"5px 7px",font:"9px monospace",letterSpacing:.7}}>{children}</span>}
function ImageStage({lead,state,onOpen}){const hero=state?.images?.[0]?.proxyUrl;return <button onClick={onOpen} style={{height:220,width:"100%",border:0,padding:0,background:"#02070a",position:"relative",overflow:"hidden",cursor:"pointer",textAlign:"left"}}>{hero?<img src={hero} alt={lead.address||"property"} style={{width:"100%",height:"100%",objectFit:"cover",transform:"scale(1.025)"}}/>:<div style={{height:"100%",display:"grid",placeItems:"center",background:"radial-gradient(circle at 50% 30%,#10313a,#02070a 65%)"}}><div style={{textAlign:"center",fontFamily:"monospace",color:C.muted}}><div style={{fontSize:26,color:C.cyan,marginBottom:6}}>EV</div>{state?.status==="unavailable"?"SOURCE UNAVAILABLE":"ACQUIRING · CROPPING · ANALYZING"}</div></div>}<div style={{position:"absolute",top:10,left:10,padding:"6px 9px",background:"#001014df",border:`1px solid ${C.line}`,color:C.cyan,font:"10px monospace"}}>{state?.status==="ready"?`EAGLEVIEW · ${state.images.length} VIEW${state.images.length===1?"":"S"}`:"LIVE IMAGE PIPELINE"}</div><div style={{position:"absolute",right:10,top:10,padding:"8px 10px",background:"#001014e8",border:`1px solid ${WINDOW_COLOR[lead.opportunity_window]||C.cyan}`,color:WINDOW_COLOR[lead.opportunity_window]||C.cyan,fontWeight:900,fontSize:20}}>{lead.opportunity_score}</div><div style={{position:"absolute",left:10,bottom:10,right:10,display:"flex",gap:6,flexWrap:"wrap"}}><Tag>{lead.opportunity_window}</Tag><Tag>{lead.lifecycle_stage}</Tag>{lead.storm_signal?<Tag hot>STORM SIGNAL</Tag>:null}</div></button>}
function LeadCard({lead,state,onOpen}){return <article style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:12,overflow:"hidden",boxShadow:"0 14px 38px #0008"}}><ImageStage lead={lead} state={state} onOpen={onOpen}/><div style={{padding:14}}><div style={{color:C.cyan,font:"10px monospace",letterSpacing:1}}>PROPERTY INTELLIGENCE</div><h3 style={{margin:"6px 0 3px",fontSize:17}}>{lead.address||lead.id}</h3><div style={{color:C.muted,fontSize:12}}>{[lead.city,lead.county,lead.state].filter(Boolean).join(" · ")}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:12}}><Gauge label="EVIDENCE" value={lead.evidence_score}/><Gauge label="CONFIDENCE" value={lead.confidence_score} suffix="%"/><Gauge label="ROOF" value={lead.roof_visual_score}/></div><div style={{marginTop:12,paddingTop:10,borderTop:`1px solid ${C.line}`,fontSize:11,color:C.muted}}><b style={{color:C.text}}>NEXT:</b> {lead.next_action}</div></div></article>}
function DetailDrawer({lead,state,onClose}){if(!lead)return null;const imgs=state?.images||[];return <div onClick={onClose} style={{position:"fixed",inset:0,zIndex:999,background:"#000c",overflowY:"auto",padding:12}}><section onClick={e=>e.stopPropagation()} style={{maxWidth:1180,margin:"20px auto",background:C.bg,border:`1px solid ${C.cyan}`,boxShadow:"0 0 70px #00ffff20",borderRadius:14,overflow:"hidden",color:C.text}}><div style={{padding:16,display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div><div style={{font:"10px monospace",color:C.cyan,letterSpacing:2}}>AEROLEADAI / PROPERTY TWIN</div><h2 style={{margin:"5px 0"}}>{lead.address}</h2><div style={{color:C.muted}}>{lead.opportunity_window} · {lead.lifecycle_stage} · Opportunity {lead.opportunity_score}</div></div><button onClick={onClose} style={{background:"transparent",border:0,color:C.text,fontSize:30,cursor:"pointer"}}>×</button></div>{imgs.length?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:6,padding:6,background:"#010407"}}>{imgs.slice(0,6).map((im,i)=><img key={im.token||i} src={im.proxyUrl} alt={`Property view ${i+1}`} style={{width:"100%",height:330,objectFit:"cover"}}/>)}</div>:<div style={{height:320,display:"grid",placeItems:"center",borderTop:`1px solid ${C.line}`,borderBottom:`1px solid ${C.line}`,color:C.muted}}>Professional imagery is {state?.status||"queued"}.</div>}<div style={{padding:16,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}><Gauge label="OPPORTUNITY" value={lead.opportunity_score}/><Gauge label="EVIDENCE" value={lead.evidence_score}/><Gauge label="CONFIDENCE" value={lead.confidence_score} suffix="%"/><Gauge label="VALIDATION" value={lead.validation_score}/><Gauge label="ROOF VISUAL" value={lead.roof_visual_score}/><Gauge label="FRESHNESS" value={Math.round((lead.freshness||0)*100)} suffix="%"/></div><div style={{padding:"0 16px 18px"}}><div style={{border:`1px solid ${C.line}`,padding:13,background:C.panel}}><b style={{color:C.cyan}}>AI ACTION</b><div style={{marginTop:5}}>{lead.next_action}</div><small style={{display:"block",marginTop:8,color:C.muted}}>Imagery is evidence. Roof condition remains an AI observation until human/field verification confirms it.</small></div></div></section></div>}

export default function V22MaxConsole({limit=100}){
  const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[filter,setFilter]=useState("ALL"),[selected,setSelected]=useState(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/v22max/scorecard?limit=${limit}`,{cache:"no-store"});const j=await r.json();if(!j.success)setError(j.error||"Scorecard unavailable");setData(j)}catch(e){setError(e.message||"Network error")}finally{setLoading(false)}},[limit]);
  useEffect(()=>{load()},[load]);
  const leads=data?.ranked||data?.top||[];const visible=useMemo(()=>filter==="ALL"?leads:leads.filter(x=>x.opportunity_window===filter),[leads,filter]);const imageStates=useImageQueue(leads,4);const ready=Object.values(imageStates).filter(x=>x.status==="ready").length;const acquiring=Object.values(imageStates).filter(x=>x.status==="acquiring").length;
  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 85% 0,#0a3038 0,transparent 36%),#02070b",color:C.text,padding:18,fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1500,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:15,flexWrap:"wrap",padding:"8px 0 18px"}}><div><div style={{color:C.cyan,font:"11px monospace",letterSpacing:2}}>AEROLEADAI / v2.2 MAX</div><h1 style={{fontSize:"clamp(28px,5vw,48px)",margin:"4px 0",letterSpacing:-1}}>Visual Opportunity Command</h1><p style={{color:C.muted,maxWidth:820,margin:0}}>Every prospect is ranked, visually enriched, cropped into a property card, and paired with evidence, confidence, roof, storm, freshness, and next-action intelligence.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Gauge label="LEADS" value={data?.total||0}/><Gauge label="IMAGES READY" value={ready}/><Gauge label="ACQUIRING" value={acquiring}/><Gauge label="SALES READY" value={data?.sales_ready||0}/></div></header>{data?.dataMode==="demo"&&<div style={{padding:10,border:`1px solid ${C.amber}`,color:C.amber,marginBottom:14}}>DEMO DATA — synthetic, not live.</div>}{error&&<div style={{color:C.red}}>{error}</div>}<nav style={{display:"flex",gap:7,flexWrap:"wrap",marginBottom:16}}>{["ALL","NOW","0-3 MONTHS","3-6 MONTHS","6-12 MONTHS","WATCH"].map(x=><button key={x} onClick={()=>setFilter(x)} style={{padding:"8px 11px",background:filter===x?C.cyan:C.panel,border:`1px solid ${filter===x?C.cyan:C.line}`,color:filter===x?"#001014":C.text,borderRadius:6,cursor:"pointer",fontWeight:700}}>{x}</button>)}<button onClick={load} style={{padding:"8px 11px",background:C.panel,border:`1px solid ${C.line}`,color:C.cyan,borderRadius:6,cursor:"pointer",marginLeft:"auto"}}>REFRESH</button></nav>{loading?<div style={{padding:40,textAlign:"center",color:C.muted}}>Ranking leads and launching image acquisition…</div>:<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}>{visible.map(lead=><LeadCard key={lead.id} lead={lead} state={imageStates[lead.id]} onOpen={()=>setSelected(lead)}/>)}</section>}<DetailDrawer lead={selected} state={selected?imageStates[selected.id]:null} onClose={()=>setSelected(null)}/></div></main>;
}
