"use client";
import {useEffect,useMemo,useState} from "react";
const PANEL="#131c2b",LINE="#22304a",TEXT="#dfe6ee",MUTE="#77839a",AMBER="#f5b942",GREEN="#4fc98e",RED="#ef5a6f",BLUE="#4fa3e3";
const sv=l=>l.lat!=null&&l.lon!=null?`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${l.lat},${l.lon}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${l.address||""}, ${l.city||""}, ${l.state||"MN"}`)}`;
const money=v=>v?`$${Number(v).toLocaleString()}`:"SEARCHING";
function PropertyImage({lead}){const list=lead.image_candidates||[],[idx,setIdx]=useState(0),item=list[idx];if(!item)return <div style={{height:150,display:"grid",placeItems:"center",border:`1px dashed ${LINE}`,borderRadius:8,color:AMBER,background:"#0a111b"}}>IMAGE CRAWL QUEUED</div>;return <div><img src={item.url} alt={lead.address||"Property"} onError={()=>setIdx(i=>i+1)} style={{width:"100%",height:150,objectFit:"cover",borderRadius:8,border:`1px solid ${LINE}`,background:"#0a111b"}}/><div style={{fontSize:10,color:MUTE,marginTop:4}}>{item.label} · fallback {idx+1}/{list.length}</div></div>}
export default function ImmediateIntelligencePanel(){
 const[d,setD]=useState(null),[err,setErr]=useState(""),[territory,setTerritory]=useState({zip:"",city:"",county:""});
 const qs=useMemo(()=>{const p=new URLSearchParams({limit:"500"});Object.entries(territory).forEach(([k,v])=>v&&p.set(k,v));return p.toString()},[territory]);
 useEffect(()=>{let live=true;const load=()=>fetch(`/api/v22max/scorecard?${qs}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||j.success===false)throw new Error(j.error||"Lead API failed");return j}).then(j=>{if(live){setD(j);setErr("")}}).catch(e=>live&&setErr(e.message));load();const t=setInterval(load,30000);return()=>{live=false;clearInterval(t)}},[qs]);
 const leads=d?.ranked||[];
 return <section style={{marginBottom:18}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"end",marginBottom:12}}><div><div style={{fontSize:11,letterSpacing:1.4,color:AMBER,fontFamily:"monospace"}}>TOP 500 · IMMEDIATE CONTRACTOR PROSPECTS</div><div style={{fontSize:13,color:err?RED:MUTE,marginTop:4}}>{err||(d?`${d.total} prospects · ${d.certified} certified · ${d.collecting} verifying · ${d.crawler_jobs} crawler jobs queued`:"Loading current territory intelligence…")}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{["zip","city","county"].map(k=><input key={k} value={territory[k]} onChange={e=>setTerritory(x=>({...x,[k]:e.target.value}))} placeholder={`Territory ${k}`} style={{background:PANEL,border:`1px solid ${LINE}`,borderRadius:6,padding:"8px 9px",color:TEXT}}/>)}<button onClick={()=>setTerritory({zip:"",city:"",county:""})} style={{background:"transparent",border:`1px solid ${BLUE}`,borderRadius:6,color:BLUE,padding:"8px 10px",cursor:"pointer"}}>All territory</button></div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginBottom:12}}>{[["PROSPECTS",d?.total],["AVG SIGNATURE",d?.avg_signature_score],["CERTIFIED",d?.certified],["SALES READY",d?.sales_ready],["STORM FLAGGED",d?.storm_flagged]].map(([k,v])=><div key={k} style={{background:PANEL,border:`1px solid ${LINE}`,borderRadius:8,padding:10}}><div style={{fontSize:10,color:MUTE,fontFamily:"monospace"}}>{k}</div><div style={{fontSize:22,fontWeight:800,color:BLUE}}>{v??"—"}</div></div>)}</div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:12,maxHeight:760,overflowY:"auto",paddingRight:3}}>{leads.slice(0,500).map((l,i)=><article key={l.id} style={{background:PANEL,border:`1px solid ${LINE}`,borderRadius:10,padding:12}}><PropertyImage lead={l}/><div style={{fontSize:10,color:AMBER,fontFamily:"monospace",marginTop:8}}>#{i+1} · {l.opportunity_window} · OPPORTUNITY {l.opportunity_score} · SIGNATURE {l.signature_score}</div><div style={{fontWeight:700,margin:"5px 0"}}>{l.address||l.id}</div><div style={{fontSize:11,color:l.score_status==="CERTIFIED"?GREEN:AMBER}}>{l.score_status}{l.certified_score!=null?` · CERTIFIED SCORE ${l.certified_score}`:" · CRAWLERS VERIFYING"}</div><div style={{fontSize:12,color:MUTE,marginTop:4}}>{[l.city,l.state||"MN",l.zip||l.zip_code||l.postal_code].filter(Boolean).join(" · ")}</div><div style={{fontSize:12,marginTop:4}}>Year built {l.year_built??"SEARCHING"} · Value {money(l.assessed_value)}</div><div style={{fontSize:12,marginTop:4}}>Permit {l.lanes?.permit||"collecting"} · Storm {l.lanes?.storm||"collecting"} · Imagery {l.lanes?.imagery||"collecting"}</div><div style={{fontSize:12,marginTop:4}}>Evidence {l.evidence_score??"—"} · Confidence {l.confidence_score??"—"}% · Roof {l.roof_visual_score??"—"} · Penalty {l.contradiction_penalty||0}</div><div style={{marginTop:7,padding:8,background:"#0a111b",borderRadius:7,fontSize:10,color:MUTE}}>{(l.crawler_jobs||[]).slice(0,3).map(j=><div key={j.lane}>↳ {j.lane.toUpperCase()}: {j.objective}</div>)}</div><div style={{fontSize:11,color:MUTE,marginTop:7}}>{l.next_action}</div><a href={sv(l)} target="_blank" rel="noreferrer" style={{display:"inline-block",marginTop:7,color:BLUE,fontSize:12}}>Open property location</a></article>)}</div>
 </section>;
}
