"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import ImageLab from "../../../components/v22max/ImageLab";
const C={line:"#173b45",cyan:"#35eee8",ice:"#ecfbff",muted:"#78949d",amber:"#ffb14a",red:"#ff765f",green:"#4dffb3"};
function esriFallback(lat,lon){const a=Number(lat),o=Number(lon);if(!Number.isFinite(a)||!Number.isFinite(o))return null;const d=.0008;return `https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=${o-d},${a-d},${o+d},${a+d}&bboxSR=4326&imageSR=4326&size=1200,800&format=jpg&f=image`}
function mapsUrl(l){const q=[l.address||l.property_address,l.city,l.state||"MN",l.zip].filter(Boolean).join(", ");return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q||`${l.lat},${l.lon}`)}`}
export default function Page(){const[prospects,setProspects]=useState([]),[selected,setSelected]=useState(null),[leads,setLeads]=useState([]),[loading,setLoading]=useState(true),[boost,setBoost]=useState(null),[media,setMedia]=useState({}),[lab,setLab]=useState(null);const queue=useRef([]),active=useRef(0);
 async function supercharge(name){setBoost({name,status:"SUPERCHARGING",queued:0});try{const r=await fetch("/api/contractor-prospects/supercharge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({businessName:name})});const d=await r.json();setBoost({name,status:d.ok?"SUPERCHARGED":"BOOST ERROR",queued:d.queued||0,matched:d.matched||0,mode:d.mode,error:d.error});return d}catch(e){setBoost({name,status:"BOOST ERROR",error:e.message});}}
 async function load(name,doBoost=false){setLoading(true);try{if(name&&doBoost)await supercharge(name);const r=await fetch(`/api/contractor-prospects${name?`?name=${encodeURIComponent(name)}`:""}`,{cache:"no-store"});const d=await r.json();if(d.ok){setProspects(d.prospects||[]);if(name){setSelected(d.contractor);setLeads(d.leads||[]);const s={};for(const l of d.leads||[])if(l.id&&l.images?.length)s[l.id]={images:l.images,loading:false};setMedia(s)}}}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);function pump(){while(active.current<4&&queue.current.length){const l=queue.current.shift();if(!l||media[l.id])continue;active.current++;setMedia(s=>({...s,[l.id]:{loading:true,images:[]}}));const address=[l.address||l.property_address,l.city,l.state||"MN",l.zip].filter(Boolean).join(", ");fetch("/api/eagleview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address,lat:l.lat,lon:l.lon,wait:true,maxWaitMs:18000})}).then(r=>r.json()).then(x=>setMedia(s=>({...s,[l.id]:{loading:false,images:x.images||[]}}))).catch(()=>setMedia(s=>({...s,[l.id]:{loading:false,images:[]}}))).finally(()=>{active.current--;setTimeout(pump,30)})}}
 useEffect(()=>{queue.current=leads.filter(l=>!media[l.id]);pump()},[leads]);const ready=useMemo(()=>Object.values(media).filter(x=>x.images?.length).length,[media]);
 return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 80% 0,#0a3440,transparent 35%),#03070a",color:C.ice,fontFamily:"Inter,system-ui",padding:24}}><div style={{maxWidth:1550,margin:"auto"}}><a href="/twincities" style={{color:C.cyan,textDecoration:"none"}}>← TWIN CITIES ENGINE</a><header style={{margin:"22px 0"}}><div style={{font:"11px monospace",letterSpacing:".18em",color:C.cyan}}>AEROLEADAI / TWIN CITIES CONTRACTOR NETWORK</div><h1 style={{fontSize:"clamp(38px,6vw,70px)",margin:"8px 0",lineHeight:.92}}>Contractor Supercharge</h1><p style={{color:C.muted,maxWidth:900}}>The Twin Cities database stays populated. Open any contractor and AeroLeadAI immediately shifts validation, evidence, permit, storm and imagery resources toward that contractor's service area without stopping the rest of the network.</p></header>{loading&&<div style={{color:C.cyan,fontFamily:"monospace"}}>ACQUIRING TERRITORY + REDIRECTING EVIDENCE WORKERS…</div>}
 {!selected&&!loading&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}>{prospects.map((p,i)=><article key={p.business_name} style={card}><div style={{font:"10px monospace",color:C.cyan}}>CONTRACTOR #{i+1}</div><h2>{p.business_name}</h2><b style={{color:C.green}}>Network score {p.prospect_score}/100</b><p style={{color:C.muted,minHeight:38}}>Coverage: {(p.service_area_cities||[]).join(" · ")||"Twin Cities network"}</p><button onClick={()=>load(p.business_name,true)} style={btn(C.cyan)}>OPEN + SUPERCHARGE →</button></article>)}</div>}
 {selected&&!loading&&<section><button onClick={()=>{setSelected(null);setLeads([]);setMedia({});setBoost(null);load()}} style={btn(C.muted)}>← ALL CONTRACTORS</button><div style={{...card,marginTop:14,borderColor:C.cyan}}><div style={{display:"flex",justifyContent:"space-between",gap:15,flexWrap:"wrap"}}><div><div style={{font:"10px monospace",color:C.amber}}>ACTIVE CONTRACTOR FOCUS</div><h2 style={{fontSize:30,margin:"6px 0"}}>{selected.business_name}</h2><div style={{color:C.muted}}>{(selected.service_area_cities||[]).join(" · ")}</div></div><div><b style={{fontSize:20,color:boost?.status==="SUPERCHARGED"?C.green:C.cyan}}>{boost?.status||"ACTIVE"}</b><div style={{font:"11px monospace",color:C.muted,marginTop:5}}>{boost?.queued||0} PRIORITY JOBS · {boost?.matched||leads.length} MATCHED</div><button onClick={()=>supercharge(selected.business_name)} style={{...btn(C.amber),marginTop:10}}>⚡ SUPERCHARGE AGAIN</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:15}}><Stat l="LIVE LEADS" v={leads.length}/><Stat l="IMAGERY READY" v={ready}/><Stat l="EVIDENCE WORKERS" v={boost?.queued||0}/></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(315px,1fr))",gap:16,marginTop:18}}>{leads.map((l,i)=><Lead key={l.id||i} l={l} i={i} m={media[l.id]||{images:l.images||[]}} open={(images,index)=>setLab({images,index,title:l.address||"Property"})}/>)}</div></section>}
 </div>{lab&&<ImageLab {...lab} onClose={()=>setLab(null)}/>}</main>}
const card={border:`1px solid ${C.line}`,background:"linear-gradient(145deg,#071218,#040a0e)",padding:18,borderRadius:14,boxShadow:"0 18px 60px #0007"};function Lead({l,i,m,open}){const e=m.images||[],f=esriFallback(l.lat,l.lon),d=e[0]||(f?{url:f}:null),g=e.length?e:(d?[d]:[]);return <article style={{...card,padding:0,overflow:"hidden"}}><button onClick={()=>d&&open(g,0)} style={{height:225,width:"100%",border:0,padding:0,background:"#020608",position:"relative",color:C.ice}}>{d?<img src={d.proxyUrl||d.url} style={{width:"100%",height:"100%",objectFit:"cover"}} alt="property"/>:<span>MAP VIEW AVAILABLE</span>}<b style={{position:"absolute",top:10,right:10,background:"#001217dd",padding:8,color:C.cyan}}>#{i+1}</b></button><div style={{padding:15}}><h3 style={{margin:"0 0 6px"}}>{l.address||l.property_address}</h3><div style={{color:C.muted,fontSize:12}}>{l.city} · {e.length?"EAGLEVIEW":"ESRI / MAP FALLBACK"}</div><a href={mapsUrl(l)} target="_blank" rel="noreferrer" style={{...btn(C.green),display:"block",textAlign:"center",textDecoration:"none",marginTop:12}}>OPEN PROPERTY ↗</a></div></article>}
function Stat({l,v}){return <div style={{border:`1px solid ${C.line}`,padding:12}}><b style={{fontSize:26,color:C.cyan}}>{v}</b><div style={{font:"9px monospace",color:C.muted}}>{l}</div></div>}function btn(color){return{padding:"10px 13px",background:"transparent",border:`1px solid ${color}`,color,borderRadius:8,cursor:"pointer",fontSize:11,fontWeight:900}}
