/** AeroLeadAI v2.2 MAX — deterministic lead intelligence. */
export const V22MAX_VERSION = "2.2.0-MAX";
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp01=x=>Math.max(0,Math.min(1,x));
export function norm(value,min,max){if(max<=min)return .5;return clamp01((num(value)-min)/(max-min));}
export function evidenceCompleteness(row={}){const fields=[row.evidence_score,row.confidence_score,row.validation_score,row.roof_visual_score,row.assessed_value,row.priority_score];return fields.filter(v=>v!==null&&v!==undefined&&v!=="").length/fields.length;}
export function stormSignal(row={}){const text=JSON.stringify(row.storm_evidence||row.weather_evidence||{}).toLowerCase();return /(hail|wind|severe|storm|damage|tornado|straight-?line|derecho)/.test(text)?1:0;}
export function ageInDays(row={},now=Date.now()){const ts=row.updated_at||row.evidence_updated_at||row.created_at;const t=ts?Date.parse(ts):NaN;if(!Number.isFinite(t))return null;return Math.max(0,Math.floor((now-t)/86400000));}
export function freshnessFactor(row={}, {halfLifeDays=45,now=Date.now()}={}){const age=ageInDays(row,now);if(age===null)return .6;return clamp01(Math.pow(.5,age/halfLifeDays));}
export function defaultRange(){const range=name=>({min:0,max:name==="assessed_value"?1000000:100});return{priority:range("priority_score"),evidence:range("evidence_score"),value:range("assessed_value"),roof:range("roof_visual_score"),validation:range("validation_score")};}
export function opportunityScore(row,statsRange,opts={}){const s=statsRange||defaultRange();const priority=norm(row.priority_score,s.priority.min,s.priority.max);const evidence=norm(row.evidence_score,s.evidence.min,s.evidence.max);const value=norm(row.assessed_value,s.value.min,s.value.max);const roof=norm(row.roof_visual_score,s.roof.min,s.roof.max);const validation=norm(row.validation_score,s.validation.min,s.validation.max);const base=priority*.42+evidence*.18+roof*.12+validation*.10+value*.08+stormSignal(row)*.06+evidenceCompleteness(row)*.04;return Math.round(clamp01(base)*freshnessFactor(row,opts)*100);}
export function opportunityWindow(score,fresh){if(score>=70&&fresh>=.5)return"NOW";if(score>=55)return"0-3 MONTHS";if(score>=40)return"3-6 MONTHS";if(score>=25)return"6-12 MONTHS";return"WATCH";}
export function lifecycleStage(row={}){const c=evidenceCompleteness(row);const validated=num(row.validation_score)>=60;const contacted=Boolean(row.crm_status||row.contacted_at||row.status);if(contacted)return"ENGAGED";if(validated&&c>=.8)return"SALES-READY";if(c>=.5)return"QUALIFYING";if(c>0)return"DISCOVERED";return"UNQUALIFIED";}
export function nextAction(row={},enrichment={}){const stage=enrichment.lifecycle_stage||lifecycleStage(row);const fresh=enrichment.freshness??freshnessFactor(row);const completeness=enrichment.evidence_completeness??evidenceCompleteness(row);if(stage==="ENGAGED")return"Follow up on the open conversation.";if(fresh<.35)return"Re-verify evidence — the record has decayed past useful confidence.";if(stage==="SALES-READY")return"Route to contractor for inspection booking.";if(!row.roof_visual_score)return"Fetch roof imagery — no visual score on record.";if(!row.validation_score)return"Run validation pass — lead is unvalidated.";if(completeness<.5)return"Enrich core evidence fields before scoring is trustworthy.";return"Hold in radar; re-check on the next evidence cycle.";}
export function enrichLead(row={},statsRange=null,opts={}){const fresh=freshnessFactor(row,opts),score=opportunityScore(row,statsRange,opts),completeness=evidenceCompleteness(row),stage=lifecycleStage(row);const enrichment={opportunity_score:score,opportunity_window:opportunityWindow(score,fresh),freshness:Number(fresh.toFixed(4)),age_days:ageInDays(row),evidence_completeness:Number(completeness.toFixed(4)),lifecycle_stage:stage,storm_signal:stormSignal(row)};return{...row,...enrichment,next_action:nextAction(row,enrichment)};}
export function scorecard(rows=[],statsRange=null,opts={}){const enriched=rows.map(r=>enrichLead(r,statsRange,opts));const avg=key=>enriched.length?Number((enriched.reduce((a,e)=>a+num(e[key]),0)/enriched.length).toFixed(4)):0;const tierCount={};for(const e of enriched)tierCount[e.opportunity_window]=(tierCount[e.opportunity_window]||0)+1;const ranked=[...enriched].sort((a,b)=>b.opportunity_score-a.opportunity_score);return{total:enriched.length,avg_opportunity_score:avg("opportunity_score"),avg_freshness:avg("freshness"),avg_evidence_completeness:avg("evidence_completeness"),windows:tierCount,sales_ready:enriched.filter(e=>e.lifecycle_stage==="SALES-READY").length,storm_flagged:enriched.filter(e=>e.storm_signal).length,ranked:ranked.slice(0,Math.min(Number(opts.rankedLimit||100),500)),top:ranked.slice(0,10)};}
